javax:
    sql:
        DataSource:
            shipping-db:
                dataSourceClassName: com.mysql.cj.jdbc.MysqlDataSource
                dataSource:
                    serverName: shipping-db
                    port: 3306
                    databaseName: shipping
                    user: shipping
                    password: pass
